CREATE TABLE PERSON (
D_ID  VARCHAR2(10) PRIMARY KEY NOT NULL,
D_NAME VARCHAR2(20) NOT NULL,
L_NAME VARCHAR2(20),
ADDRESS VARCHAR2(30)
);
DESC PERSON;

CREATE TABLE CAR(
PALET_NUMBER VARCHAR2(15) PRIMARY KEY ,
CAR_MODEL VARCHAR2(15),
COLOR VARCHAR2(12),
CAR_DATE DATE

);
DESC CAR;

CREATE TABLE ACCIDENT(
REP_NUMBER  NUMBER(10) PRIMARY KEY,
REGISTER_DATE DATE,
LOC  VARCHAR2(20)
);

DESC ACCIDENT

CREATE TABLE OWNER(
D_ID VARCHAR2(10)  NOT NULL,
PALET_NUMBER VARCHAR2(15),
FOREIGN KEY(D_ID) REFERENCES PERSON(D_ID),
FOREIGN KEY (PALET_NUMBER) REFERENCES CAR(PALET_NUMBER)
);
DESC OWNER;

CREATE TABLE PARTICIPATION(
D_ID VARCHAR2(10),
PALET_NUMBER VARCHAR2(15),
REP_NUMBER NUMBER(10),
DAMAGE_AMOUNT NUMBER(10),
FOREIGN KEY(D_ID) REFERENCES PERSON(D_ID),
FOREIGN KEY(PALET_NUMBER) REFERENCES CAR(PALET_NUMBER),
FOREIGN KEY(REP_NUMBER) REFERENCES ACCIDENT(REP_NUMBER)
);

DESC participation;

INSERT INTO PERSON VALUES('DR0001','NASRATULLAH','SABERZAI','KABUL');
